site_name: ""
extra_css:
  - /css/extra.css

nav:
  - Home:
      - Introduction: index.md
      - Getting Started: getting_started.md
  - Modules:
      - User Management: modules/index.md
      - Dashboards: modules/dashboards.md
      - Patients: modules/patients.md
      - Orders: modules/orders.md
      - Results: modules/results.md
      - Appointments: modules/appointments.md
      - Biometrics: modules/biometrics.md
      - Organizations: modules/organizations.md
      - Locations: modules/locations.md
      - Providers: modules/providers.md
      - Diagnosis Codes: modules/diagnosis_codes.md
      - Test: modules/tests.md
      - Insurance: modules/insurances.md
      - Medications: modules/medications.md
      - Ask on Order Entry: modules/AOE.md
      - Notifications: modules/notifications.md
      - Banner Messages: modules/banner_messages.md
  - Team: team/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  logo: /img/Labxchange_Logo_v2.svg
  favicon: /img/labX-X-logo.svg

  palette:
    - scheme: default
      primary: black
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - admonition
  font:
    text: Poppins
    code: Roboto Mono

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/circle-info
