site_name: LabXChange

nav:
  - Home:
    - Another Home:  index.md
    - Sample Module: index.md
  - Sample Nav: sample_module/sample.md
  - About: about.md

theme:
    name: material
    palette:
        primary: 'teal'
        accent: 'indigo'
    features:
        - navigation.tabs
        - navigation.top
        - navigation.sections
    font:
        text: Roboto
        code: Roboto Mono